version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ConnectionStrings__AppDbContext=Data Source=/app/data/authExample.db
    volumes:
      - sqlite-data:/app/data
    networks:
      - auth-network

volumes:
  sqlite-data:

networks:
  auth-network:
    driver: bridge